### ISSUE TITLE
需要一個煞氣的 LOGO

### ISSUE THREAD

**Issue by vinta** [codetengu/headquarters#1]
地方的 CodeTengu 需要 LOGO
除了 LOGO 之外還得要有標準字體

主要的元素應該是「天狗」（不然還能是什麼？！）
考慮到大部份網站的頭像都是正方形，希望 LOGO 不要太長或太寬
至少要有 png, svg, ico 格式
其他想到再補

**Comment by vinta** [comment]
現在這個 icon 是在 [NounProject](https://thenounproject.com/) 買的
先擋一下
但是看久了其實也是挺帥的

**Comment by kkc** [comment]
真的是頗帥氣的...

**Comment by vinta** [comment]
哈哈哈哈～

**Comment by vinta** [comment]
感謝 @rocavence （還有他老婆）設計的 LOGO
closed by @6c5617ec9c800bb83c6019b0c9e4a2203f5ee032
