### ISSUE TITLE
Weekly issue 76：2017/02/20 出刊

### ISSUE THREAD

**Issue by kkdai** [CodeTengu/headquarters#102]
請問一下 @vinta  主編，這次剩下三天要發的 issue 76 是哪些人負責？

我可以幫忙提供五篇  :)

**Comment by yhsiang** [comment]
我也可以 ._.\~/

**Comment by vinta** [comment]
哈哈，難得大家興致這麼好
不過我是打算 76 期是 2/20 才要發ㄋㄟ
如果要在 2/13 發，今天才公布會太趕啦

@kkdai @yhsiang 所以 76 期 2/20 出刊，兩位 ok？

**Comment by uranusjr** [comment]
~~大家這麼有興致是情人節太閒嗎~~

**Comment by kkdai** [comment]
~~說好不提衛生紙的梗~~

**Comment by yhsiang** [comment]
@uranusjr 都留言了，就一起吧 wwww

**Comment by vinta** [comment]
差點又忘了公佈
本期陣容：

@vinta
@kkdai 
@yhsiang 

有問題請說！

**Comment by kkdai** [comment]
我的部分好了 :)

**Comment by vinta** [comment]
我也好了，剩 @yhsiang 了啊

**Comment by yhsiang** [comment]
@vinta 主編大大，我也好了！

**Comment by vinta** [comment]
歐也，已排程，關！
