### ISSUE TITLE
第二次碼天狗聚餐

### ISSUE THREAD

**Issue by vinta** [CodeTengu/headquarters#124]
為了慶祝 CodeTengu Weekly 即將滿 100 期，[上次](https://github.com/CodeTengu/headquarters/issues/121)大家提議吃燒肉，不過我很久沒吃燒肉了，沒有什麼口袋名單，所以 —— 以下開放大家推薦餐廳！

原本想說大家直接用 👍 來投票，不過剛剛看到 [gh-polls](https://github.com/tj/gh-polls)，好像很帥，要提議的人可以試試～

然後照老規矩，我會另外再 email 給各位 [Doodle](https://doodle.com/) 的連結，讓大家挑一下自己有空的時間。不過是說都 2017 年了，要跟很多人喬時間有沒有先進一點的辦法？

**Comment by kkdai** [comment]
燒肉只好叫 @yhsiang 丟幾個口袋名單來...   小弟有個不情之請.. 目前服喪中... 可以的話請約八月..  (感恩唷)

**Comment by hiroshiyui** [comment]
我這次還是跳過啦～不過如果各位大大有來 COSCUP 歡迎找我交換名片 :bowing_man:

**Comment by vinta** [comment]
時間和地點已經確定啦，記得收 email 或是到 https://my.curated.co/codetengu/issues/28449 這裡看。下禮拜見！ 

特別一下 cc @mingderwang @yhsiang
