### ISSUE TITLE
@vinta 下週換誰寫?

### ISSUE THREAD

**Issue by mingderwang** [CodeTengu/headquarters#176]

**Comment by theJian** [comment]
@vinta where are you?

**Comment by vinta** [comment]
啊不好意思，最近身體狀況不太好，舊疾復發，怠慢怠慢了。

這一期就不指定，開放大家認領，老規矩每人最多五篇，湊滿 12 篇發刊：
https://my.curated.co/codetengu/issues/34687

**Comment by wancw** [comment]
Moved to #177
