### ISSUE TITLE
問卷調查

### ISSUE THREAD

**Issue by saiday** [codetengu/headquarters#2]

**Comment by vinta** [comment]
我剛剛抽菸的時候正想到要開這個 issue 的說

**Comment by vinta** [comment]
@saiday 小海說的那兩個服務叫什麼？

**Comment by saiday** [comment]
@vinta 
[JotForm](http://www.jotform.com/myforms/)
[SurveyMonkey](https://www.surveymonkey.com/)
[TypeForm](http://www.typeform.com/)

**Comment by saiday** [comment]
TypeForm 似乎可以弄的很 Fancy，我剛剛一直在玩

**Comment by vinta** [comment]
剛剛發現一個中國的服務 https://jinshuju.net/
給你參考一下
