### ISSUE TITLE
找一個可以負責 Ruby 及 Rails 領域的 curator

### ISSUE THREAD

**Issue by fukuball** [codetengu/headquarters#25]
現在的編制是：

@fukuball PHP, Machine Learning
@saiday iOS, Android
@tzangms Management, Growth hacking（兼任 JavaScript）
@vinta Python, DevOps
@wancw Node.JS, Android, Java
@adamp33  Front-Ends

**Comment by fukuball** [comment]
@vinta 我目前是找 @tonytonyjan 負責 Ruby 及 Rails 部分，他說 11 月可以加入編制
https://github.com/tonytonyjan

**Comment by tonytonyjan** [comment]
請多指教 :smile:

**Comment by wancw** [comment]
我現在都找到啥就放啥，有需要 focus 在某些領域嗎？

**Comment by vinta** [comment]
@wancw 的領域不就是 node.js 和 android 嗎，不會很雜啊

**Comment by vinta** [comment]
@tonytonyjan 那我們就先暫定 2015/11/09 那一期（issue 15）好了，可以嗎？
我晚點會邀請你進 weekly 的系統

**Comment by tonytonyjan** [comment]
@vinta 可，字數約多少？

**Comment by vinta** [comment]
@tonytonyjan 我剛剛有寄邀請給你了，寄到你 GitHub 上的那個 email
我們現在用的是 https://curated.co/ 的服務
你可以先感受一下

字數不限，你可以寫五個字也可以寫 500 個字

**Comment by vinta** [comment]
Done!
