### ISSUE TITLE
想一下文案，中文和英文

### ISSUE THREAD

**Issue by vinta** [CodeTengu/headquarters#3]
目前想到的：

## CodeTengu

Developers matter.
CodeTengu is an organization of the developers, for the developers, and by the developers.

## CodeTengu Weekly

A developer-driven weekly newsletter that curates awesome contents with arbitrary commentaries.

CodeTengu Weekly（碼天狗週刊）是一份開發者導向的 IT 技術週刊，讓你用最少的時間獲取最有價值的資訊。適合所有患有資訊焦慮、氣血循環不順以及性受挫的軟體工程師們。

**Comment by vinta** [comment]
致力於解決 developers 之間的資訊不對稱！

**Comment by wancw** [comment]
"The weekly you only need ever!"

**Comment by vinta** [comment]
Done!
