### ISSUE TITLE
短链地址似乎被 GFW 认证了，墙内无法直接访问

### ISSUE THREAD

**Issue by halfcrazy** [CodeTengu/headquarters#32]
北京联通

**Comment by vinta** [comment]
@halfcrazy 竟然有這種事？！

你是說 http://cur.at/ 嗎？

**Comment by halfcrazy** [comment]
@vinta 对的。

**Comment by tzangms** [comment]
該不會得自己弄個電子報系統了 :/

**Comment by halfcrazy** [comment]
@tzangms 感觉链接没必要一定是短链，使用原始地址也可以的

**Comment by tzangms** [comment]
主要因為 curated 這個系統是用 cur.at 來做連結點擊統計的呀 ~

**Comment by vinta** [comment]
@halfcrazy 有哪些沒有被屏蔽的短連結服務可以在中國使用？bitly?

**Comment by vinta** [comment]
@halfcrazy 我剛剛把連結的 domin 換成 link.codetengu.com 了，再麻煩你測試看看？

**Comment by tzangms** [comment]
原來可以用自己的 sub domain, 帥喔

**Comment by halfcrazy** [comment]
@vinta LGTM
