### ISSUE TITLE
寫一份給新加入 curator 的 guideline

### ISSUE THREAD

**Issue by vinta** [CodeTengu/headquarters#35]
詳細地說明一下我們的運作模式
或是也可以另外寫一份用來邀請別人加入的 guideline

**Comment by fukuball** [comment]
1. GMT+8 時區的每個禮拜日 22:00 截稿，每一期會從目前的 curator 名單中選出三位來負責當期的內容，每期每位 curator 要挑選至少 3-5 篇技術文章簡短分享。
2. 簡短分享文字裡的中文和半形的英文、數字、符號之間要插入空白，規則參考 https://github.com/vinta/paranoid-auto-spacing

**Comment by fukuball** [comment]
3. 主編排好每期 curator  後，若 curator 預期當週有不可預期的情況無法製作刊物，直接在 issue 上要求換 curator。

**Comment by vinta** [comment]
目前的 readme 似乎就夠了
