### ISSUE TITLE
Survey #1 軟體工程師的感情生活

### ISSUE THREAD

**Issue by saiday** [codetengu/headquarters#4]
1. 性別
2. 年齡
3. 使用的語言
4. 交過女友的數量
5. 在哪裡認識的 (複選)
6. 在關係中是主導還是被控制的
7. 對方是相關領域的嗎

expectation: 找出寫哪個語言的工程師有最健全的感情生活

**Comment by vinta** [comment]
附註：要在 weekly 第一期中把這個問券調查丟出去

**Comment by saiday** [comment]
附註：Weekyly 第一期改丟 #5
