### ISSUE TITLE
新年特刊 Weekly issue 28：2016/02/04 出刊

### ISSUE THREAD

**Issue by vinta** [CodeTengu/headquarters#46]
因為有人（@tzangms）忘了 Issue 27 要交稿，所以導致 27 這一期只有兩個 curator 上場打擊，不過反正也快過年啦，將錯就錯，我們在這個禮拜四 2016/02/04 臨時加開一期 Issue 28 新年特刊，除了讓 @tzangms 補寫他的份之外，這一期大家想寫就寫，就不排名單啦！

不過為了避免之前因為 email 內文太長，在 Gmail 裡會被截斷的情況再次發生，這次想寫的人可能寫個一兩則就好啦，不用寫到五則那麼多。

cc @saiday @fukuball @wancw @adamp33 @mingderwang @kako0507 @chiahsien

**Comment by fukuball** [comment]
OK, 沒問題～

**Comment by chiahsien** [comment]
我可以

**Comment by fukuball** [comment]
@vinta 新年特刊我的部分已經好了～

**Comment by tzangms** [comment]
是想逼死我嗎 各位 

我還在認真的準備 recuit

**Comment by fukuball** [comment]
只寫一篇應該還好啦 XDD

**Comment by chiahsien** [comment]
我也好囉

**Comment by fukuball** [comment]
新年特刊快到期了，剛剛看還沒有什麼內容，所以我又加碼了一篇～

**Comment by chiahsien** [comment]
其他人有要一起來玩這一期嗎？沒有的話我可以再多貢獻一兩篇。

**Comment by saiday** [comment]
我我我！但我想寫一則就好勒！

**Comment by vinta** [comment]
我也會寫一則！

**Comment by tzangms** [comment]
我寫好了 5 則了!!

**Comment by saiday** [comment]
我也寫好了！爽！

**Comment by tzangms** [comment]
標題要叫啥？

「小海上週缺稿懲罰補交作業，新年放送特輯!」 嗎?

**Comment by chiahsien** [comment]
聽來頗酷！

**Comment by vinta** [comment]
Done!
