### ISSUE TITLE
LinkedIn Group or 公眾號

### ISSUE THREAD

**Issue by kkdai** [CodeTengu/headquarters#56]
既然有人以看碼天狗為[專業興趣](https://tw.linkedin.com/in/kametang)，我們是否有要成立專業的 Group 在 LinkedIn 主要是更新訊息，

**Comment by vinta** [comment]
但是應該沒有人喜歡在 LinkedIn 上看東西吧？
LinkedIn 這個產品本質上就讓人討厭啊

**Comment by maoyang** [comment]
我也很喜歡看碼天狗, 要不要來我的slack建一個碼天狗的channel

**Comment by appleboy** [comment]
Golang Taiwan 的 Slack 很缺水，可以去那邊建立頻道 XD

**Comment by wancw** [comment]
嗯……其實有個 Telegram Channel 。

是說，要的話，應該是建個碼天狗 Slack？ XD

**Comment by vinta** [comment]
現在幾乎每個語言、每個領域都有人開了 Slack 了
其實沒有必要再多一個 CodeTengu 的 Slack（雖然其實我當初有申請）
所以我是覺得有 https://gitter.im/CodeTengu/headquarters 就夠了

而且每個 Slack 都要一組帳號密碼實在很煩吶
Gitter 可以直接用 GitHub 登入很方便啊

**Comment by vinta** [comment]
但是開一個微信公眾號倒是不錯
有開過 https://github.com/CodeTengu/headquarters/issues/19 說要做

但是微信公眾號是不是要有中國的手機門號才能開啊？

**Comment by appleboy** [comment]
Slack 真的很麻煩   光是台灣就不知道幾個群組了  每個都要一組帳號密碼，好累 XD  還是繼續用 gitter，未讀的也會寄信給你  潮爽

**Comment by uranusjr** [comment]
Slack 就是工作導向的，台灣流行的開法有點不健康⋯⋯贊成目前 Gitter 的方案不錯。Telegram 用的人太少，不然也是個好選擇啦。
