### ISSUE TITLE
Curated 被併購的備案 

### ISSUE THREAD

**Issue by kkdai** [CodeTengu/headquarters#59]
收到 Curated 被 Litmus! 併購的信件
發這個 issue 看看有沒有需要尋求發信系統的備案

- [goodbits](https://goodbits.io/) : 個人有架過（使用界面還不錯，不過限制比較多)

**Comment by vinta** [comment]
Curated 被併購還是可以繼續用啊
反正不是被 Yahoo! 併購
不然就自己寫一個（剁手）！

@kkdai goodbits 有什麼限制？它的 Pro Plan 看起來好像不錯啊

**Comment by kkdai** [comment]
@vinta  主要是我們之前在 gitter 上討論過的幾個問題:

- 免費限制讀者200
- 根據  jhihguan 說 goodbits 不太穩

**Comment by vinta** [comment]
現在 Curated 的每個月 69 美金都在付了啊

**Comment by vinta** [comment]
統一在 https://github.com/CodeTengu/headquarters/issues/73 討論
