### ISSUE TITLE
Weekly #1

### ISSUE THREAD

**Issue by vinta** [codetengu/headquarters#6]
預計 8/3 發佈

**Comment by tzangms** [comment]
嗚嗚 我現在才一篇

**Comment by vinta** [comment]
離發刊日期剩沒幾天了吼

**Comment by tzangms** [comment]
我看了一下, 大家的連結會不會有點太多了, 還是說真的都很值得分享?

這 Weekly 一下去就得每週出了對吧 XD

**Comment by vinta** [comment]
三個人加起來的連結確實是有點多，不過大部份的讀者應該也不會對我們三個人推的東西都有興趣吧？他實際上可能只會看一兩個人推的連結而已，所以還好啦我覺得

**Comment by tzangms** [comment]
我只推五個 link, 我覺得這樣差不多, 再多好像壓力就有點大了 ( 我最近都覺得  weekly 連結多, 就壓力大 )

**Comment by vinta** [comment]
第一期已發，close
