### ISSUE TITLE
Issue 45 的標題不符合物理

### ISSUE THREAD

**Issue by uranusjr** [CodeTengu/headquarters#67]
引用[維基百科](https://zh.wikipedia.org/wiki/速度)：

> 速度（英語：Velocity）是描述物體運動快慢和方向的物理量。物體在一段時間 𝚫*t* 內的平均速度 *v̅* 是它在這段時間裡的位移 𝚫*r* 和時間間隔之比：
>
> *v̅* = 𝚫*r* / 𝚫*t*
>
> [略] 在物理學中，速度和速率是兩個不同的概念。速度是向量，具有大小和方向；速率則純粹指物體運動的快慢，是純量，沒有方向。

[以及](https://zh.wikipedia.org/wiki/速率)：

> 速率是一個純量，只有大小，沒有方向。它的因次是長度除以時間。速度的因次和速率相同，但速度是有方向的向量。

由上面的敘述可知，計算速度需要時間與**位移向量**，因此除了距離之外，還需要**方向**。當女朋友需要時間與距離時，她希望計算的應該是速率，而非速度。

**Comment by wancw** [comment]
其實這是一個隱藏的哏：「但我們沒有方向啊！！」（誤）

**Comment by saiday** [comment]
> Issue 45 我女朋友說她最近需要一些時間跟距離，請問她是不是要算速度？

會不會這個可憐的男孩子知道他女朋友即將要移動的方向，真的好悲情喔

**Comment by wancw** [comment]
@saiday 😢

**Comment by uranusjr** [comment]
QQ

**Comment by vinta** [comment]
Fixed

請 @saiday 出來跟大家道歉

**Comment by seanmars** [comment]
每個禮拜都很期待標題(喂

**Comment by c9s** [comment]
XD

**Comment by wayne5540** [comment]
笑死我ＸＤ
