### ISSUE TITLE
codetengu.com 會產生 HTTP 404

### ISSUE THREAD

**Issue by uranusjr** [CodeTengu/headquarters#69]
然後頁面上會有個 Return home 連結⋯⋯同樣導向 codetengu.com，仍然是 404。

是不是應該把這個 domain 先重導向到 weekly.codetengu.com 比較好？

**Comment by vinta** [comment]
啊可惡，昨天換 nameserver 的時候改爛啦

**Comment by vinta** [comment]
已解決，關
