### ISSUE TITLE
尋求 Curated 的替代方案

### ISSUE THREAD

**Issue by vinta** [CodeTengu/headquarters#73]
<img width="988" alt="screen shot 2016-06-29 at 15 23 00" src="https://cloud.githubusercontent.com/assets/652070/16444430/80e38242-3e10-11e6-8fda-158c89b78115.png">

我們現在每個月花在 [Curated](https://curated.co/) 的費用是 69 美金
然後在可預見的未來 費用的下一個級距會是 129 美金
但是 129 美金真的太貴啦
所以我們可能得找個替代方案了

大概有幾個方案：
1. 像 [@kkdai](https://github.com/CodeTengu/headquarters/issues/59) 提到的改用其他家的服務（例如 [Goodbits](https://goodbits.io/)）
2. 自己寫一套發布、管理 weekly 的系統
3. 找一套 open source 的專案，二次開發（例如 [mailtrain](https://github.com/andris9/mailtrain)）
4. 尋求贊助或 donate

**Comment by uranusjr** [comment]
剛看了一下 Goodbits 好像有限 contributor 數量（除了詢價的 Business），似乎不太適合這個專案。

**Comment by kkdai** [comment]
Goodbits 看來得詢價... 自己寫的話除了 email 之外， host site 錢也得算進去...

**Comment by fukuball** [comment]
感覺自己寫比較彈性且即使 host + 發信應該價錢也比較便宜，但真的蠻花時間的，寄信的機制還有編輯器都需要花一點功，要做可能會選二次開發。

另外找贊助也是一種選擇啦，如果真的找不到贊助，還有一個存活方式就是 curator 一起攤，vinta 用 paypal 或其他可用線上付款機制收款當成基金，只是之前沒有跟加入的人說到要攤錢，而且也不是長久之計

**Comment by vinta** [comment]
如果要自己開發的話
為了減少開發的工作量
我覺得可以乾脆不要做網站後台
所有發布、編輯或管理的功能都寫成 command-line tools
有點類似 static site generator 的做法
但是不管是自己開發還是二次開發
要花的時間和後續的 maintain 想起來就覺得麻煩吶

主要是 Curated 的 $129 真的太貴，就算贊助或是大家攤也很難撐太久

**Comment by kkdai** [comment]
@vinta 其實可以用 github 吧 issue 分 folder 裡面直接放 markdown 。 編輯直接把文章貼在貼在GitHub.  這樣只要寫發佈來抓資料夾寄信就好。不過 curated 能撈用戶資料嗎？

**Comment by vinta** [comment]
@kkdai 直接用 GitHub issue 好像也不錯

Curated 可以匯出 subscribers 名單

**Comment by fukuball** [comment]
如果用 GitHub Issue 那問題就只剩下發信了～ lambdabaku 可能也可以拿來做這件事

**Comment by vinta** [comment]
最低限度要做的事大概有：

- 每一期的 web 頁面
- 往期的 Archive 頁面
- subscribe / unsubscribe 的功能
- 從草稿（GitHub issue）生成 email 內容和 web 頁面
- 寄信
- 數據統計

**Comment by kkdai** [comment]
整理一下我的想法:

1. 當期編輯直接把 markdown 放在 github 名為該 issue number 的資料夾中 (ex: issue 49 -> "49")
2. 寫一個 script 把該資料夾檔案整理成電子報（加上頁頭，頁尾)，發信出去．
3. 並且把要發送的內容 (MD) 寫入 github page 作為瀏覽頁面． （jekyll, hugo 皆可)
4. 訂閱部分比較麻煩，要用 bitbucket (github private) 來管理，一樣是寫入與讀取．

短網址 -> tweetthat?
數據統計 -> google analytic

基本概念用 git 當資料庫，反正文章都是公開，應該沒啥需要資料庫．
關於訂戶部分可以考慮用資料庫，如果有需要其他分析 ;P

不知道這樣如何？？

**Comment by uranusjr** [comment]
看起來不錯，可能會有些小地方需要處理（例如圖片上傳），不過大致上網站瀏覽應該都可以用 static site 辦到。新用戶從網站上訂閱之後要怎麼接到 repository 可能就要稍微想一下。

關於短網址，目前已經有的要怎麼辦？有需要 backward compatibility 嗎？

**Comment by yhsiang** [comment]
我沒什麼意見，需要做什麼直接 assign 給我就好了 😸

**Comment by jhihguan** [comment]
之前有看過這個是self host的mail service
付一次錢就可以自架
https://sendy.co/
不過沒有使用過@@

**Comment by saiday** [comment]
另一個選擇～
https://www.getrevue.co/

**Comment by fukuball** [comment]
價格真的便宜超多～

**Comment by kkdai** [comment]
不是很確定patreon 這個是不是 Codetengu 拉贊助?  Refer to https://www.patreon.com/fatih
