### ISSUE TITLE
issue 57 裡 Why I consider if/else idiomatic Go 的 link 很像不對?

### ISSUE THREAD

**Issue by mingderwang** [CodeTengu/headquarters#82]
Why I consider if/else idiomatic Go
這一篇講解了很基本的 IF / ELSE 的使用方式．特別是在 Golang 的 Error Handle 部分． 大家在判斷回傳值中的 Error ，是否有注意到他的變數生命週期？ 有沒有想過如何寫會讓人更容易了解？

很推薦這一篇來好好學習一下

nicerobot.org  Permalink

**Comment by kkdai** [comment]
糟糕... 被砍掉...   orz
