### ISSUE TITLE
issue 58, streetvoice.com 工作機會 link 不對

### ISSUE THREAD

**Issue by mingderwang** [CodeTengu/headquarters#83]
目前是 https://streetvoice.com/p/jobs/

**Comment by vinta** [comment]
甘蝦，已修正！

**Comment by tzangms** [comment]
謝謝 @mingderwang !

[n4oKYFlAcv2AU](https://camo.githubusercontent.com/23160ad02945b282fc42a2d6e6212194d0516d9e/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f6e346f4b59466c4163763241552f67697068792e676966>)
