### ISSUE TITLE
找一個可以負責 web frontend 領域的 curator

### ISSUE THREAD

**Issue by vinta** [codetengu/headquarters#9]
這樣戰線大致上就完整了

現在的編制是：

- @fukuball PHP, Machine Learning
- @saiday iOS, Android
- @tzangms Management, Growth hacking（兼任 JavaScript）
- @vinta Python, DevOps

**Comment by vinta** [comment]
之後 weekly 運作的模式大概會是每期三個 curators，大家輪流上，每個人最多 5 篇 links

**Comment by vinta** [comment]
如果之後可以有 .NET 或 Java 系的能力者加入也不錯

**Comment by tzangms** [comment]
昨天在想, 會不會之後會辦個 CodeTengu Conf

**Comment by vinta** [comment]
哈哈哈哈如果真的有那麼一天一定超酷的啊

**Comment by vinta** [comment]
但是完全可以先辦個幾場線下的小一點的活動啊

**Comment by tzangms** [comment]
CodeTengu 互助會

**Comment by vinta** [comment]
Conference 可以請幾個 show girls 來舉牌

**Comment by saiday** [comment]
互助會真的蠻吸引人的

**Comment by tzangms** [comment]
剛才突然想到, 是不是該用個 https://gitter.im/

**Comment by vinta** [comment]
好，我去申請一個！

但是我們要拿來幹嘛？

**Comment by tzangms** [comment]
只是想說在 issue 聊天, 是不是該改用 gitter 比較方便?

倒是, 也許 gitter 可以用來收集反饋?

**Comment by vinta** [comment]
@tzangms @saiday 開好啦，在 README 就可以連進去

**Comment by fukuball** [comment]
@vinta 我的 Email 是 fukuball[at]gmail.com，昨天忘記回了，哈哈，前端我再問問看 Pinkoi 的 Adam

**Comment by vinta** [comment]
@fukuball 我禮拜五的時候就寄 http://curated.co/ 的邀請給你了啊

**Comment by fukuball** [comment]
@vinta 喔，看到了～

**Comment by vinta** [comment]
@fukuball 第四期（8/24 那一期）就換你了，記得準備一下喔

**Comment by fukuball** [comment]
@vinta ok~

**Comment by fukuball** [comment]
前端的部分目前問過 Adam Wang 了，他覺得很有興趣，下週想找個時間跟我們一起見面聊聊，等他告訴我時間，我們一起約約看。
https://www.facebook.com/adamp3

**Comment by vinta** [comment]
好喔！

**Comment by vinta** [comment]
我們有 @adamp33 了，關！
